#!/bin/sh
## Usage: ./gvim FILE
## Description: Opens terminal running nvim with $FILE
## Deps: Neovim, misc/term-exec

for file in "$@"
do
  if [ -f "$file" ]; then
    term-exec nvim $file
    break
  fi
done
