#!/bin/sh

FILTER="${1:-*}"
AWSPROFILE=${2:-default}

# Retrieve all instances matching the query (formatted: '<NameTag> <Hostname>')
aws ec2 describe-instances --profile "$AWSPROFILE" --filter Name=tag:Name,Values="*$FILTER*" |
    jq --raw-output '.Reservations[]
                     | .Instances[]
                     | select(.State.Name == "running")
                     | (.Tags[] | select(.Key == "Name").Value) + " " + .PublicDnsName'
