#!/bin/sh

SYNTAX=$1
export TERM_EXEC_NAME=popwin
TMPFILE_DIR=/tmp/vim-anywhere
TMPFILE=$TMPFILE_DIR/doc-$(date +"%y%m%d%H%M%S")

mkdir -p $TMPFILE_DIR
touch $TMPFILE

chmod o-r $TMPFILE

if [ ! -z "SYNTAX" ]; then
  gvim -c "set syntax=$SYNTAX" -c ':set wrap' -c ':set linebreak' $TMPFILE
else
  gvim  -c ':set wrap' -c ':set linebreak' $TMPFILE
fi

cat $TMPFILE | xclip -selection clipboard
