#!/bin/sh

TMPFILE_DIR=/tmp/vim-anywhere
TMPFILE=$TMPFILE_DIR/doc-$(date +"%y%m%d%H%M%S")

mkdir -p $TMPFILE_DIR
touch $TMPFILE

chmod o-r $TMPFILE
gvim -c ':set wrap' -c ':set linebreak' $TMPFILE
cat $TMPFILE | xclip -selection clipboard
