#!/bin/sh

if [ ! -f ~/.mpw ]; then
    echo "~/.mpw does not exist!"
    exit
fi

# load mpw (master password) config
MPW_CONFIG="$(cat ~/.mpw)"
# format list of sites
SITES="$(echo "$MPW_CONFIG" | tr "\t" " " | tr -s ' ' | cut -d' ' -f1)"

# prompt user to select a site (interactive use fzf, otherwise use rofi)
if [[ -t 0 ]]; then
    SELECTED_SITE="$(echo "$SITES" | fzf-tmux --prompt='site: ')"
else
    SELECTED_SITE="$(echo "$SITES" | rofi -dmenu -i -lines 20 -width 30 -p 'site: ')"
fi

# prompt for the user to enter the master password (interactive use normal prompt, otherwise use rofi)
if [[ -t 0 ]]; then
    echo -n "Password:"
    read -s MASTER_PASSWORD
else
    MASTER_PASSWORD="$(echo "" | rofi -password -dmenu -i -lines 1 -width 30 -p 'password: ')"
fi

# look up matching mpw entry for selected site
SELECTED_ENTRY="$(echo "$MPW_CONFIG" | tr "\t" " " | tr -s ' ' | grep -i "^$SELECTED_SITE\s" | head -n 1)"
# extract selected site value from mpw entry
SELECTED_SITE_VALUE="$(echo "$SELECTED_ENTRY" | cut -d' ' -f2)"
# extract selected site type from mpw entry (max, long, basic, etc)
SELECTED_SITE_TYPE="$(echo "$SELECTED_ENTRY" | cut -d' ' -f3)"
# extract the selected site counter from the mpw entry
SELECTED_SITE_COUNTER="$(echo "$SELECTED_ENTRY" | cut -d' ' -f4)"

# Invoke mpwc to generate site specific password and symbols
MPWC_OUTPUT="$(echo "$MASTER_PASSWORD" | mpwc -t "$SELECTED_SITE_TYPE" -c "$SELECTED_SITE_COUNTER" "$SELECTED_SITE_VALUE" -i)"
PASSWORD="$(echo "$MPWC_OUTPUT" | cut -d' ' -f2)"
SYMBOLS="$(echo "$MPWC_OUTPUT" | cut -d "]" -f1 | cut -c 2-)"

# put the password in the clipboard
echo -n "$PASSWORD" | xsel --clipboard

# Display popup notification with mpw symbols
notify-send "./mpwc" "Copied password to clipboard ($SYMBOLS)"

# Verify clipster is running, exit otherwise
clipster -o > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo 'Not using clipster, password will not be removed from clipboard'
    exit
fi

# remove clip from clipster after 30 seconds
echo "\nDeleting password from clipoard in 30 seconds..."
sleep 30
echo -n "$PASSWORD" | clipster -r --clipboard
